POST http://localhost:3001/products HTTP/1.1
content-type: application/json

{
   "name": "Producto 6",
   "code": "0006",
   "price": 50,
   "currentStock": 12,
   "minStock": 1,
   "maxStock": 50
}
